/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var c=Object.defineProperty;var t=Object.getOwnPropertyDescriptor;var s=Object.getOwnPropertyNames;var g=Object.prototype.hasOwnProperty;var u=(n,o)=>{for(var e in o)c(n,e,{get:o[e],enumerable:!0})},m=(n,o,e,d)=>{if(o&&typeof o=="object"||typeof o=="function")for(let i of s(o))!g.call(n,i)&&i!==e&&c(n,i,{get:()=>o[i],enumerable:!(d=t(o,i))||d.enumerable});return n};var r=n=>m(c({},"__esModule",{value:!0}),n);var P={};u(P,{default:()=>l});module.exports=r(P);var a=require("obsidian"),l=class extends a.Plugin{async onload(){console.log("Loading CV Plugin"),this.addRibbonIcon("document","CV Plugin",()=>{new a.Notice("CV Plugin is active!")})}};
