/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var t=Object.defineProperty;var a=Object.getOwnPropertyDescriptor;var d=Object.getOwnPropertyNames;var g=Object.prototype.hasOwnProperty;var u=(o,n)=>{for(var i in n)t(o,i,{get:n[i],enumerable:!0})},P=(o,n,i,c)=>{if(n&&typeof n=="object"||typeof n=="function")for(let e of d(n))!g.call(o,e)&&e!==i&&t(o,e,{get:()=>n[e],enumerable:!(c=a(n,e))||c.enumerable});return o};var m=o=>P(t({},"__esModule",{value:!0}),o);var r={};u(r,{default:()=>l});module.exports=m(r);var s=require("obsidian"),l=class extends s.Plugin{async onload(){console.log("Loading CV Plugin Test"),this.addRibbonIcon("document","CV Plugin Test",()=>{let n=new s.Notice("CV Plugin Test is active!")})}async onunload(){console.log("Unloading CV Plugin Test")}};
